# Generated by Django 2.2 on 2019-04-06 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='webapp.Product')),
            ],
        ),
    ]
